#!/usr/bin/expect -f

set timeout 300
set password "B075@#ax/980tec"

# 1. Conectar e compactar src
spawn ssh -o StrictHostKeyChecking=no root@69.62.103.58
expect "password:"
send "$password\r"
expect "#"

send "cd /var/www/clinicrafabarros-backend/\r"
send "tar -czf src_backup.tar.gz src tsconfig.json package.json\r"
send "exit\r"
expect eof

# 2. Baixar
spawn scp -o StrictHostKeyChecking=no root@69.62.103.58:/var/www/clinicrafabarros-backend/src_backup.tar.gz /Users/arbtechinfo.ia/Projetos\ 2025/clinicrafabarros-backend/
expect "password:"
send "$password\r"
expect eof
